# Generated by Django 5.2 on 2025-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_pedido_id_lineapedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
